server:
  port: 4000

spring:
  application:
    name: crowd-auth
#  配置thymeleaf文件位置
  thymeleaf:
    suffix: .html
#    当前文件夹可以自定义命名，但是static文件夹名不可变
    prefix: classpath:/templates/

#配置eureka客户相关功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

#配置日志显示级别
logging:
  level:
    com.yama.crowd: debug
    
    