server:
  port: 80

spring:
  application:
    name: crowd-zuul

#配置eureka客户相关功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

#配置日志显示级别
logging:
  level:
    com.yama.crowd: debug
# 配置zuul的路由规则
zuul:
  routes:
    auth:
      service-id: crowd-auth
      path: /**
  ignored-services: '*'
  sensitive-headers: '*'
# 此处解决后端服务重定向导致用户浏览的 host 变成 后端服务的 host 问题
  add-host-header: true
  
  
#防止远程调用方法读取超时，连接超时
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
