server:
  port: 8000

spring:
  application:
    name: crowd-zuul

#配置eureka客户相关功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

#配置日志显示级别
logging:
  level:
    com.yama.crowd: debug
    
    
# 配置zuul的路由规则