server:
  port: 6000

spring:
  application:
    name: crowd-order
  #  配置thymeleaf文件位置
  thymeleaf:
    suffix: .html
    #    当前文件夹可以自定义命名，但是static文件夹名不可变
    prefix: classpath:/templates/
    cache: false
    mode: HTML
  profiles:
    active: dev
  #    配置session共享配置项
  session:
    store-type: redis


#配置eureka客户相关功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

#配置日志显示级别
logging:
  level:
    com.yama.crowd: debug


#防止远程调用方法读取超时，连接超时,因为第一次连接redis时，会时间比较长，放置读取失败
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000