server:
  port: 1000

spring:
  application:
    name: crowd-eureka

#配置eureka
eureka:
  instance:
#    配置eureka主机地址
    hostname: localhost
  client:
#    指定客户端访问eureka地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#   是否从eureka服务器获取注册表信息
    fetch-registry: false
#    客户端是否注册到eureka服务器中
    register-with-eureka: false