server:
  port: 2000
#为当前应用命名
spring:
  application:
    name: crowd-mysql
# 配置mybatis集成的数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/project_crowd?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: yanruyi
    driver-class-name: com.mysql.cj.jdbc.Driver
#    配置数据连接池实现
    type: com.alibaba.druid.pool.DruidDataSource

#配置eureka客户相关功能
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
      
#配置mybatsi的配置文件位置
mybatis:
#  配置xml配置文件中参数缩写
  type-aliases-package: com.yama.crowd
#  配置映射文件的位置
  mapper-locations: classpath*:/mybatis/*Mapper.xml

#配置日志显示级别
logging:
  level:
    com.yama.crowd: debug
